#!/usr/bin/env python3


import argparse
import os
from pathlib import Path
import subprocess
import sys


_FZ_CLIPBOARD_HISTORY_FILE_STRING = os.getenv(
    "FZ_CLIPBOARD_HISTORY_FILE", os.path.join(Path.home(), ".fz_clipboard_history")
)


def _parse_args():
    argparser = argparse.ArgumentParser(
        description="Redirect standard input to yeet-impl and add it to the clipboard history file.",
        epilog="Set $FZ_CLIPBOARD_HISTORY_FILE to specify the clipboard history file. "
        + "The one currently in use is: \n"
        + "\t"
        + _FZ_CLIPBOARD_HISTORY_FILE_STRING,
        formatter_class=argparse.RawTextHelpFormatter,
    )

    return argparser.parse_args()


def main():
    _parse_args()

    stdin = sys.stdin.buffer.read()

    completed_process = subprocess.run(["yeet-impl"], check=True, input=stdin)

    with open(_FZ_CLIPBOARD_HISTORY_FILE_STRING, "ab") as fz_clipboard_history_file:
        fz_clipboard_history_file.write(stdin + b"\x00")

    return completed_process.returncode


if __name__ == "__main__":
    sys.exit(main())
