#!/usr/bin/env python3


"""
Any code blocks or lines with an “unwrap” class will have their contents parsed
using Pandoc, then spliced into the document (inside a Div or Span). The
content must be in “pandoc-json” format, which you can get by passing the -t
json option to Pandoc.

This is a reimplimentation of https://github.com/Warbo/panhandle.
"""


import io
import panflute as pf
import sys


def _panhandle_filter_code_block(elem, doc):
    if type(elem) is not pf.CodeBlock:
        return None

    if not "unwrap" in elem.classes:
        return None

    elem.classes.remove("unwrap")

    if not elem.text:
        return pf.Div(attributes=elem.attributes, classes=elem.classes)

    return pf.Div(
        *pf.convert_text(elem.text, input_format="json"),
        attributes=elem.attributes,
        classes=elem.classes,
    )


def _panhandle_filter_code(elem, doc):
    if type(elem) is not pf.Code:
        return None

    if not "unwrap" in elem.classes:
        return None

    elem.classes.remove("unwrap")

    if not elem.text:
        return pf.Span(attributes=elem.attributes, classes=elem.classes)

    return pf.Span(
        *[
            inline
            for para in pf.convert_text(elem.text, input_format="json")
            for inline in para.content.list
        ],
        attributes=elem.attributes,
        classes=elem.classes,
    )


def main():
    pf.toJSONFilters([_panhandle_filter_code_block, _panhandle_filter_code])

    return 0


if __name__ == "__main__":
    sys.exit(main())
