#!/usr/bin/env sh

set -eEu

usage() {
	cat << HEREDOC
Usage:
	$(basename -- "$0") [FILE] | command
	command | $(basename -- "$0") [FILE] | command
HEREDOC
}

vipe() (
	if [ $# -ge 1 ]; then
		file="$1"
	else
		# Only remove the temp file
		file="$(mktemp)"
		trap "rm --force -- '$file'" EXIT
	fi

	# Send stdin, if it exists, to the temp file
	if [ ! -t 0 ]; then
		cat - >> "$file"
	fi

	# Edit the temp file
	${EDITOR:-vim} -c 'set nofixendofline' "$file" < /dev/tty > /dev/tty

	# Send the temp file to stdout
	cat "$file"
)

while getopts h opt; do
	case $opt in
		h)
			usage

			exit 0
			;;
		*)
			{
				echo "Try '$(basename -- "$0") -h' for more information."
			} 1>&2

			exit 1
			;;
	esac
done

if [ $# -gt 1 ]; then
	{
		echo "$(basename -- "$0"): Unexpected operands"
		echo "Try '$(basename -- "$0") -h' for more information."
	} 1>&2

	exit 1
fi

vipe "$@"
