#!/usr/bin/env bash

usage="Usage: command | $(basename -- "$0") [FILE] | command"

while getopts h OPT; do
	case $OPT in
		h)
			echo "$usage"

			exit 0
			;;
		*)
			exit 1
			;;
	esac
done

if [[ $# -gt 1 ]]; then
	{
		echo "$(basename -- "$0"): unexpected operands"
		echo
		echo "$usage"
	} 1>&2

	exit 1
fi

if [[ -n $1 ]]; then
	file=$1
else
	# Only remove the temp file
	file=$(mktemp) || exit 1
	trap 'rm -f -- "$file"' EXIT
fi

# Send stdin, if it exists, to the temp file
if [[ ! -t 0 ]]; then
	cat - >> "$file"
fi

# Edit the temp file
${VISUAL:-${EDITOR:-vi}} "$file" < /dev/tty > /dev/tty || exit 1

# Send the temp file to stdout
if [[ -f "$file" ]]; then
	cat "$file"
fi
