#!/usr/bin/env bash

set -eEu -o pipefail

usage() {
	cat << HEREDOC
Usage:
	$(basename -- "$0") <command> [<args>]
	$(basename -- "$0") git quickfix diff
	$(basename -- "$0") git quickfix diffref
	$(basename -- "$0") git quickfix show
	$(basename -- "$0") git quickfix stash show
HEREDOC
}

# Open quickfix format errors from a command in Vim
qfvim() {
	local quickfix
	quickfix="$("$@" || true)"

	if [[ "$quickfix" = '' ]]; then
		{
			echo "$(basename -- "$0"): Empty quickfix"
			echo "Try '$(basename -- "$0") -h' for more information."
		} 1>&2

		exit 1
	fi

	${EDITOR:-vim} -q <(echo "$quickfix")
}

while getopts h opt; do
	case $opt in
		h)
			usage

			exit 0
			;;
		*)
			{
				echo "Try '$(basename -- "$0") -h' for more information."
			} 1>&2

			exit 1
			;;
	esac
done

if [ $# -eq 0 ]; then
	{
		echo "$(basename -- "$0"): Expected command"
		echo "Try '$(basename -- "$0") -h' for more information."
	} 1>&2

	exit 1
fi

qfvim "$@"
