#!/usr/bin/env bash

set -e

# Open quickfix format errors from a command in Vim
qfvim() {
	local quickfix
	quickfix="$("$@")"

	if [[ "$quickfix" = '' ]]; then
		exit 1
	fi

	vim -q <(echo "$quickfix")
}

qfvim "$@"
