#!/usr/bin/env bash

usage="Usage: $(basename $0) FORMAT FILE..."

example="Example: $(basename $0) \"mv %f %f.bak\" foo.txt bar.txt buzz.txt"

while getopts "h" OPT; do
	case "$OPT" in
		h)
			echo "$usage"
			echo
			echo "$example"

			exit 0
			;;
		*)
			exit 1
			;;
	esac
done

if [[ "$#" -lt "2" ]]; then
	{
		echo "$(basename $0): missing operands"
		echo
		echo "$usage"
		echo
		echo "$example"
	} 1>&2

	exit 1
fi

format="$1"
shift

if [[ "$format" != *"%f"* ]]; then
	{
		echo 'Format missing "%f"'
		echo
		echo "$example"
	} 1>&2

	exit 1
fi

cmds="$(mktemp)" || exit 1
trap 'rm -f "$cmds"' EXIT

for file in "$@"; do
	echo "${format//%f/\'${file//\'/\'\\\'\'}\'}" >> "$cmds"
done

if [[ -z "$EDITOR" ]]; then
	{
		echo 'EDITOR environment variable not set'
	} 1>&2

	exit 1
fi

# Edit the cmds
$EDITOR "$cmds"

if [[ ! -s "$cmds" ]]; then
	{
		echo 'No cmds to run'
	} 1>&2

	exit 1
fi

source "$cmds"
