#!/usr/bin/env bash

set -e

usage() {
	cat << HEREDOC
Usage:
	$(basename -- "$0") FORMAT FILE...

Example:
	$(basename -- "$0") \"mv %f %f.bak\" foo.txt bar.txt buzz.txt
HEREDOC
}

vicmd() {
	local format
	format="$1"
	shift

	if [[ "$format" != *%f* ]]; then
		{
			echo "$(basename -- "$0"): Format missing \"%f\""
			echo "Try '$(basename -- "$0") -h' for more information."
		} 1>&2

		exit 1
	fi

	local cmds
	cmds="$(mktemp)" || exit 1
	trap 'rm --force -- "$cmds"' EXIT

	for file in "$@"; do
		echo "${format//%f/\'${file//\'/\'\\\'\'}\'}" >> "$cmds"
	done

	# Edit the cmds
	vipe "$cmds" > /dev/null || exit 1

	if [[ ! -s "$cmds" ]]; then
		{
			echo "$(basename -- "$0"): No cmds to run"
			echo "Try '$(basename -- "$0") -h' for more information."
		} 1>&2

		exit 1
	fi

	# Run the cmds
	if [ -f "$cmds" ]; then
		source "$cmds"
	fi
}

while getopts h opt; do
	case $opt in
		h)
			usage

			exit 0
			;;
		*)
			{
				echo "Try '$(basename -- "$0") -h' for more information."
			} 1>&2

			exit 1
			;;
	esac
done

if [[ $# -lt 2 ]]; then
	{
		echo "$(basename -- "$0"): Missing operands"
		echo "Try '$(basename -- "$0") -h' for more information."
	} 1>&2

	exit 1
fi

vicmd "$@"
