#!/usr/bin/env bash

set -e

usage() {
	cat << HEREDOC
Usage:
	$(basename -- "$0")

Fuzzy find text from the clipboard history file and edit it.

Set \$FZ_CLIPBOARD_HISTORY_FILE to specify the clipboard history file. The one
currently in use is:
	"${FZ_CLIPBOARD_HISTORY_FILE:-$HOME/.fz_clipboard_history}"
HEREDOC
}

fzyedit() {
	fzyoink | vipe "$@" | yeet
}

while getopts h opt; do
	case $opt in
		h)
			usage

			exit 0
			;;
		*)
			{
				echo "Try '$(basename -- "$0") -h' for more information."
			} 1>&2

			exit 1
			;;
	esac
done

if [ $# -gt 1 ]; then
	{
		echo "$(basename -- "$0"): Unexpected operands"
		echo "Try '$(basename -- "$0") -h' for more information."
	} 1>&2

	exit 1
fi

fzyedit "$@"
