#!/usr/bin/env sh

set -e

usage() {
	cat <<HEREDOC
Usage:
	$(basename -- "$0")
HEREDOC
}

rmhooks() (
	hooks="$(echo "$(eval echo "$(git config --global --get init.templatedir)")"/hooks/*)"
	timestamp="$(date +%s)"

	for hook in $hooks; do
		local_hook="$(git rev-parse --git-dir)/hooks/$(basename "$hook")"
		if [ -f "$local_hook" ]; then
			mv "$local_hook" "${local_hook}.${timestamp}.bak"
		fi
	done
)

while getopts h OPT; do
	case $OPT in
		h)
			usage

			exit 0
			;;
		*)
			{
				echo "Try '$(basename -- "$0") -h' for more information."
			} 1>&2

			exit 1
			;;
	esac
done

rmhooks
