#!/usr/bin/env sh

set -e

usage() {
	cat <<\EOF
usage:
	git rmhooks
EOF
}

rmhooks() (
	hooks="$(echo "$(eval echo "$(git config --global --get init.templatedir)")"/hooks/*)"
	timestamp="$(date +%s)"

	for hook in $hooks; do
		local_hook="$(git rev-parse --git-dir)/hooks/$(basename "$hook")"
		if [ -f "$local_hook" ]; then
			mv "$local_hook" "${local_hook}.${timestamp}.bak"
		fi
	done
)

while getopts h OPT; do
	case $OPT in
		h)
			usage

			exit 0
			;;
		*)
			echo "Try 'git rmhooks -h' for more information."

			exit 1
			;;
	esac
done

rmhooks
