#!/usr/bin/env bash

set -e

usage() {
	cat << HEREDOC
Usage:
	$(basename -- "$0")
	$(basename -- "$0") | command
	$(basename -- "$0") > file

Fuzzy find text from yoink-impl and the clipboard history file.

Set \$FZ_CLIPBOARD_HISTORY_FILE to specify the clipboard history file. The one
currently in use is:
	"${FZ_CLIPBOARD_HISTORY_FILE:-$HOME/.fz_clipboard_history}"
HEREDOC
}

fzyoink() {
	local fz_clipboard_history_file="${FZ_CLIPBOARD_HISTORY_FILE:-$HOME/.fz_clipboard_history}"

	if [[ ! -f "$fz_clipboard_history_file" ]]; then
		touch "$fz_clipboard_history_file"
	fi

	tail --lines=100 --quiet --zero-terminated "$fz_clipboard_history_file" <(echo -en "$(yoink)\0") |
		# Remove duplicates
		uniq --zero-terminated |
		# Delete empty
		sed --null-data '/^$/d' |
		# Reverse so recent text is first
		tac --separator= - |
		fzf --preview='echo {}' --multi --read0
}

while getopts h opt; do
	case $opt in
		h)
			usage

			exit 0
			;;
		*)
			{
				echo "Try '$(basename -- "$0") -h' for more information."
			} 1>&2

			exit 1
			;;
	esac
done

if [ $# -ne 0 ]; then
	{
		echo "$(basename -- "$0"): Unexpected operands"
		echo "Try '$(basename -- "$0") -h' for more information."
	} 1>&2

	exit 1
fi

fzyoink
