#!/usr/bin/env python3


import argparse
from pathlib import Path
import os
import subprocess
import sys


_FZ_CLIPBOARD_HISTORY_FILE_STRING = os.getenv(
    "FZ_CLIPBOARD_HISTORY_FILE", os.path.join(Path.home(), ".fz_clipboard_history")
)


def _parse_args():
    argparser = argparse.ArgumentParser(
        description="Fuzzy find text from yoink-impl and the clipboard history file.",
        epilog="Set $FZ_CLIPBOARD_HISTORY_FILE to specify the clipboard history file. "
        + "The one currently in use is: \n"
        + "\t"
        + _FZ_CLIPBOARD_HISTORY_FILE_STRING,
        formatter_class=argparse.RawTextHelpFormatter,
    )

    return argparser.parse_args()


def main():
    args = _parse_args()

    with open(
        _FZ_CLIPBOARD_HISTORY_FILE_STRING, mode="br"
    ) as fz_clipboard_history_file:
        lines = fz_clipboard_history_file.read().rstrip(b"\x00").split(b"\x00")
        # Delete empty
        lines = [line for line in lines if len(line) != 0]
        # Remove duplicates
        lines = [*dict.fromkeys(lines)]
        # Reverse so recent text is first
        lines.reverse()

        completed_process = subprocess.run(
            ["fzf", "--multi", "--preview=echo {}", "--read0"],
            input=b"\x00".join(lines[-100:]),
        )

    return completed_process.returncode


if __name__ == "__main__":
    sys.exit(main())
